### PR TITLE
Update gmap-custom-marker.vue

### PR DESCRIPTION
**Pull request by manrajang**
ie not support.

### CODE REVIEW

**Comment by eregnier** [comment]
:+1: thank you @manrajang 
it is released https://www.npmjs.com/package/vue2-gmap-custom-marker

**Comment by eregnier** [comment]
Code is not working properly. I reverted for now. I'll fix this soon.

**Comment by manrajang** [comment]
i use lib in gmap clusterer example. throw exception in ie.

**Comment by eregnier** [comment]
it should be ok now with version 5.5.8 I just released. Can you confirm ?

**Pull request merged**
